/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [];
    "login.store": [];
    "logout": [];
    "password.request": [];
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ];
    "password.email": [];
    "password.store": [];
    "user-profile-information.update": [];
    "user-password.update": [];
    "password.confirm": [];
    "password.confirmation": [];
    "password.confirm.store": [];
    "two-factor.login": [];
    "two-factor.login.store": [];
    "two-factor.enable": [];
    "two-factor.confirm": [];
    "two-factor.disable": [];
    "two-factor.qr-code": [];
    "two-factor.secret-key": [];
    "two-factor.recovery-codes": [];
    "two-factor.regenerate-recovery-codes": [];
    "home": [];
    "dashboard": [];
    "wallet": [];
    "topup": [];
    "withdraw": [];
    "wallet.topup.process": [];
    "wallet.withdraw.process": [];
    "wallet.solana.request-devnet-tokens": [];
    "wallet.withdrawalEstimate": [];
    "api.withdrawal.status": [
        {
            "name": "id",
            "required": true
        }
    ];
    "profile.edit": [];
    "profile.update": [];
    "profile.destroy": [];
    "password.edit": [];
    "password.update": [];
    "appearance.edit": [];
    "two-factor.show": [];
    "register": [];
    "register.store": [];
    "verification.notice": [];
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ];
    "verification.send": [];
    "phone.login.send-otp": [];
    "phone.login.verify-otp": [];
    "phone.login.otp": [];
    "social.redirect": [
        {
            "name": "provider",
            "required": true
        }
    ];
    "social.callback": [
        {
            "name": "provider",
            "required": true
        }
    ];
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ];
  }
}

// Global window interface extension for Ziggy
declare global {
  interface Window {
    Ziggy?: any;
  }
}

export {};
